# Tratamento do csv de regiões
Para ajudar na generalização de municípios

In [2]:
import pandas as pd

df = pd.read_csv('ce-regions.csv', header=0,
                 names=['municipioCaso', 'regiaoPlanejamentoCaso'])
df

         municipioCaso regiaoPlanejamentoCaso
0              Massapê       Sertão de Sobral
1    Santana do Acaraú       Sertão de Sobral
2               Sobral       Sertão de Sobral
3             Groaíras       Sertão de Sobral
4              Meruoca       Sertão de Sobral
..                 ...                    ...
179  Santana do Cariri                 Cariri
180        Nova Olinda                 Cariri
181           Barbalha                 Cariri
182          Caririaçu                 Cariri
183       Missão Velha                 Cariri

[184 rows x 2 columns]

Transformar para UPPERCASE e remover acentuação

In [3]:
df["municipioCaso"] = df["municipioCaso"].str.upper()
df['municipioCaso'] = df['municipioCaso'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df["regiaoPlanejamentoCaso"] = df["regiaoPlanejamentoCaso"].str.upper()
df["regiaoPlanejamentoCaso"] = df['regiaoPlanejamentoCaso'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df

         municipioCaso regiaoPlanejamentoCaso
0              MASSAPE       SERTAO DE SOBRAL
1    SANTANA DO ACARAU       SERTAO DE SOBRAL
2               SOBRAL       SERTAO DE SOBRAL
3             GROAIRAS       SERTAO DE SOBRAL
4              MERUOCA       SERTAO DE SOBRAL
..                 ...                    ...
179  SANTANA DO CARIRI                 CARIRI
180        NOVA OLINDA                 CARIRI
181           BARBALHA                 CARIRI
182          CARIRIACU                 CARIRI
183       MISSAO VELHA                 CARIRI

[184 rows x 2 columns]

In [4]:
df.to_csv('ce-regions-format.csv', index=False)